# Generated by Django 4.1.7 on 2023-04-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_public_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
