# Generated by Django 4.1.7 on 2023-04-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_caption',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
