# Generated by Django 4.1.7 on 2023-04-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_public_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
